### ISSUE TITLE
Japanese vertical view is weird

### ISSUE THREAD

**Issue by arjaz** [simjanos-dev/LinguaCafe#1]
It seems to me that the layout is a bit broken
![image](https://github.com/simjanos-dev/LinguaCafe/assets/33521892/d0618f48-0a3c-42de-8679-5165acf66f21)
Great app btw!

**Comment by arjaz** [comment]
Ah, makes sense, thank you!

**Comment by systemcrash** [comment]
Reading Japanese vertically: how it's meant to be done :D
