### ISSUE TITLE
How about converting the dictionary file to TSV?

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#112]
It would be like this: convert dictionary file to TSV and then load it. 

There are some scripts for the conversion.
https://codeberg.org/GrimPixel/Dictionary_Tools

**Comment by simjanos-dev** [comment]
Wow, there are some cool dictionaries there that I don't use.

> How about converting the dictionary file to TSV? 
I'm sorry, I don't understand what would you like me to do. You want me to add these dictionaries that are missing from linguacafe?

**Comment by GrimPixel** [comment]
It would be great if they are supported.

Maybe it's just a matter of style. I believe that formats supported can be limited to one tabular and one hierarchical  and I usually choose TSV and YAML. Using specific formats means that they can be utilised in other ways, like being imported to Anki or other programs. Instead of having many parsers for all kinds of formats in different programs, I would prefer converting them once and for all.

**Comment by simjanos-dev** [comment]
I will add support for these dictionaries. 

Sorry, I'm still not sure I understood what you meant. I usually add support for dictionaries one by one, and also have a general .csv import option where you can import your own custom dictionary.

**Comment by GrimPixel** [comment]
OK, let me explain it step by step.

The goal is to utilise dictionaries in different formats in different programs. One way is to support different formats in different programs, another is to support only one tabular and one hierarchical data formats for all programs with a converter that turn other formats to the two formats.

I would prefer the second solution, because this guarantees that once they have been converted to the chosen formats, they will be available everywhere, saving the efforts of supporting different formats in different programs. I use TSV and YAML, so that different programs can use the same files. The same TSV file I import to Anki can be used to generate [altering TTS audio files](https://codeberg.org/GrimPixel/Altering_TTS) or [Tabletop Club card assets](https://codeberg.org/GrimPixel/Tabletop_Club_Text_Asset_Generator).

**Comment by simjanos-dev** [comment]
Oh, I get it. You want to store all the dictionaries in the same format. 

I think I'll just keep them in the format they come whenever possible. I understand that it would be more useful for other projects, but it complicates it for linguacafe. Some dictionaries like dict cc also do not allow me to upload it, so users would have to convert themself.

**Comment by GrimPixel** [comment]
Glad to know your thoughts. It's a good reason to keep it this way.
