### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#113]
There is no LICENSE yet. As the program is distributing contents under GPL-3.0 or AGPL-3.0, it would be one of them or another one similar to them.

**Comment by simjanos-dev** [comment]
I didn't have time to look into licenses yet, I will add a license file in the future. I've linked licenses for everything I use. 

For linguacafe itself, I don't mind if people using it in any way, as long as they don't hide that it is based on linguacafe.
