### ISSUE TITLE
Change “Kanji” to “Glyph”

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#114]
It could be generalised. Other scripts like Egyptian hieroglyphs, Tangut can be learned in a similar manner as well. DMAK, KanjiVG and other libraries can be designated for the Han script, just like a specific dictionary for a specific language.

**Comment by simjanos-dev** [comment]
This is a good idea. I do want to add the same support for Chinese, but do not know yet about adding more languages with glyphs. It sounds like there are a few of them, and they are very difficult to support, and very few people learn them. I'll add a Kanji -> Glyph refactor task to #103. 

Is Glyph the correct term for it? Glyph also seems to include regular alphabet.

**Comment by GrimPixel** [comment]
Glad to know your thoughts.

Actually, it is not limited to logograms. It can be applied on any writing system, like Brahmic scripts. Even for CJKV, one can learn Bopomofo, Kana, Hangul with it.

A character may have different glyphs, or “character forms”. for example, 戶／户／戸 are three different glyphs of the same character, a/ɑ are two different glyphs for the same character.
