### ISSUE TITLE
Different language profiles for the same user

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#115]
One combination of characters have different meanings in different languages. So it requires multiple language profiles. [Lute v3](https://github.com/jzohrab/lute-v3) has this feature.

**Comment by simjanos-dev** [comment]
Can you please elaborate more? 

I think linguacafe already works the way you described. If you find the same word twice in different languages, they are only attached to their own language. You can switch languages if you click on the selected language on the bottom left. Everything is handled separately between languages.

**Comment by GrimPixel** [comment]
Ahh, I didn't notice there. Thanks for the explanation.
