### ISSUE TITLE
Specify language-script combos instead of simply languages

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#116]
A language may have different scripts. In the ideal case, once a word is added, its corresponding text in other writing systems are generated automatically, like Kazakh, or even Korean, where the Hangul (kor-Hang) is generated from Korean mixed script (kor-Kore) directly.

**Comment by simjanos-dev** [comment]
I'm not familiar with a lot of languages that have multiple writing systems, I think it should be decided for each language separately. 

Mixed Korean is barely used to my understanding. In this case, people could use the same Korean language option in linguacafe, and treat Hanja words as separate words in the current system already. I assume it is not possible to accurately translate words between Hangul and Hanja words programmatically, if it is and it will be a popular feature request, I could add a separate language for mixed Korean and add support for connecting them.

In some languages like Norwegian, there are two written systems, but they contain different words. Same, I could add a separate language for them if people ask for it, but it would be difficult to connect words.

I am not familiar with Kazakh. If there will be a supported language, where there are multiple written scripts, and their words can be connected accurately, I could add support for generating the same words in the other language option if it's requested by people. If the words are the same, and only characters are written differently, then I could just add multiple font types for them.
