### ISSUE TITLE
Long sentence on flashcard can make clicking on buttons ("I was correct" / "Again") impossible

### ISSUE THREAD

**Issue by TheNomad11** [simjanos-dev/LinguaCafe#135]
When you have long sentences, they fill the whole flashcard, and the solution drops below it. It overlaps with the buttons "Again" and "I was correct", so that is is hard or impossible to click on them and continue the review.

![screen-2024-02-16-19-52-43](https://github.com/simjanos-dev/LinguaCafe/assets/20747629/9a4241c0-3e7e-4164-9e01-e3dea82f1f3f)

**Comment by simjanos-dev** [comment]
Thank you! I'll fix this in the next update.

In the meantime, you can use the hotkeys if you are on desktop.

![Screenshot_20240217_134903](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/41984918-ca0d-41a4-a27a-faee79bcf7bc)

**Comment by TheNomad11** [comment]
Great, perfect, thanks a lot, didn't see the hotkeys

**Comment by simjanos-dev** [comment]
I've increased the minimum height of the review cards. If the content still doesn't fit, the card's height will increase, and it will push the buttons lower. There still can be a problem if the card does not fit the screen. I will add a limit setting for example sentence's length to handle very long sentences in a later update.

The review card fix will be out in v0.8.
