### ISSUE TITLE
Minor UI issue: Library View - disappearing "Open" / reading button on detailed layout for long titles

### ISSUE THREAD

**Issue by pm3003** [simjanos-dev/LinguaCafe#136]
**Problem encountered:** I'm opening an issue in case someone fumbles 3 solid minutes like me before findng the problem:
- When the library is displayed under the _detailed layout_, the "Open" button disappears when the title is too long.

**Workarounds:**
- shorten the title 
- switch to _cover only_ layout for clickable covers
- use URL to access book.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/7607aff7-cb22-4835-bf83-23ff4667e512)

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/322f137f-c963-48ee-9e01-2c4c861eafb0)

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/55c874ed-e818-4a8e-8fef-230c59b8aacc)

**Comment by simjanos-dev** [comment]
Thank you! 

Another one I never encountered. Will fix it in the next update.

**Comment by simjanos-dev** [comment]
Fixed it, will be in v0.8.
