### ISSUE TITLE
Mac chmod command does not work. 

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#152]
The `chmod 777 -R ./ && docker compose up -d` install command returns with an error message that says "can't find the file or directory" on Mac.

This is the second time I've seen this problem, it worked when `chmod 777 -R ./` was replaced with `chmod -R 777 linguacafe` from the parent directory. 

Could someone please find a replacement install command and test it? I do not have access to a Mac, so unfortunately I can't test it.

**Comment by simjanos-dev** [comment]
Someone suggested that the problem is maybe the order of the parameters, and it should be `chmod -R 777 ./`.

**Comment by simjanos-dev** [comment]
Someone tested it on Mac, and `chmod -R 777 ./` did run successfully. Will test it on linux, and modify the readme.

**Comment by uzluisf** [comment]
I can confirm that `chmod -R 777 ./` works on macOS.

**Comment by simjanos-dev** [comment]
@uzluisf Thank you! Fixed the readme file. 

Since multiple people confirmed it works, I'll close this issue.
