### ISSUE TITLE
[Feature request] Support imports from lightnovel-crawler

### ISSUE THREAD

**Issue by Weroxig** [simjanos-dev/LinguaCafe#153]
I have a bunch of lightnovels downloaded with https://github.com/dipu-bd/lightnovel-crawler but adding each book and chapter manually will take a long time.

**Comment by simjanos-dev** [comment]
Thank you for the feature request!

This software is collecting copyrighted material, I'm not sure if I want to add it. Personally I do not have any problem with it, but I do not want to have any copyright or other legal issues with LinguaCafe.

I'll consider it later. Also, I'm planning on creating an API, so people can create tools to import from additional sources.

> adding each book and chapter manually will take a long time
You can import a whole e-pub or text file, so at least you don't have to do it chapter by chapter manually.

**Comment by simjanos-dev** [comment]
I will not implement this to avoid any copyright related issues.
