### ISSUE TITLE
[Feature Request] Ignored words should be visually different from known words

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#166]
Ignored words should be visually different from and less prominent than known words. For example, in the paragraph below the words `Harvard`, `Medical`, `social network`, etc. shouldn't be as prominent as `nelle`, `sonno`, etc.

I'm thinking either lightening or darkening the text color relative to the background but there might be a better implementation. Because this might present some accessibility issues, this could be disabled by default and users can enable it if they want.

| Before | After |
|:-------|:------|
| <img width="721" alt="image" src="https://github.com/simjanos-dev/LinguaCafe/assets/22332927/7d6d0e3f-f0d3-486b-891f-a68ef1aea189"> |  <img width="721" alt="image" src="https://github.com/simjanos-dev/LinguaCafe/assets/22332927/f040c608-fea6-4766-b2c6-b147966289d5"> |

**Comment by simjanos-dev** [comment]
Thank you! 

I think I'll implement this when I'll get to adding text theme customization.

**Comment by uzluisf** [comment]
>I think I'll implement this when I'll get to adding text theme customization.

Thanks! Btw I think it'd be worth it if you add a contribution guide. I'm primarily a backend programmer with some knowledge of React but I could take a stab at some of the tickets with a little bit of time and some guidance.

**Comment by simjanos-dev** [comment]
I added a `CONTRIBUTING.md` file, but it was a few days after I pulished it. Probably will rewrite at least some of it. I didn't expect people to be interested in it, and this is my first open source project, so I don't have any experience with it.

What things would you like to see in the contribution guide? 

> with a little bit of time and some guidance

I am happy to help with anything. I plan to write a smaller documentation for devs, but It will take months probably.

**Comment by uzluisf** [comment]
>I added a CONTRIBUTING.md file, but it was a few days after I pulished it. 

I just realized there was this after the fact.

>What things would you like to see in the contribution guide?

A few things that come to mind are:

- Quick breakdown of the tech stack, and what a developer needs installed before starting developing in LinguaCafe.
- How to start LinguaCafe in developer mode.
- Breakdown of how the app is organized (high-level), and where to start looking (e.g., app's entry point).
- Code style guidelines if any.

After writing this I've realized this is the mostly a wishlist, I think any motivated developer will get things working fairly easy by looking and poking around :).

**Comment by simjanos-dev** [comment]
> After writing this I've realized this is the mostly a wishlist, I think any motivated developer will get things working fairly easy by looking and poking around :).

Thank you! I think all are great points, and I'll try to add them to the file soon.

**Comment by simjanos-dev** [comment]
I've updated the [contributing.md](https://github.com/simjanos-dev/LinguaCafe/blob/main/CONTRIBUTING.md) file. Thank you for the feedback on what to add to it. Hope it is better than the previous one.

**Comment by simjanos-dev** [comment]
I've added a separate text color for ignored words' text. By default it is the same as regular text color, but you can change it on the new theme settings page. It will be released in v0.10
