### ISSUE TITLE
[Feature Request] Allow customization of a chapter's text

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#168]
As a user, I would like to change the text font, background color, zoom in/out, etc. solely for the chapter's text. What I've in mind is something like the settings in Brave Browser's Speedreader. Mind you, the zoom in/out and background color (via the global theme) features are already available in LinguaCafe.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/22332927/32125b77-e44c-41f8-8ff1-8e92640d432f)

**Comment by simjanos-dev** [comment]
I was planning on adding font type settings, but mostly for Asian languages. I'll just write a full font management system. You'll be able to add fonts to the storage directory, and use them in interactive texts. 

> Mind you, the zoom in/out and background color (via the global theme) features are already available in LinguaCafe.

You can also change the width of the page, and spacing between lines on the text reader's settings page.

I can add a separate color for the text's background and color. But I will implement this one as well, when I add theme customization.

**Comment by simjanos-dev** [comment]
I'll close this issue. I'll track font types in #40, and I'll track theming in #191.
