### ISSUE TITLE
[Feature Request] When importing text from a website, make the text editable

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#173]
As a user, I'd like to edit the text I'd import from a website before I make it a chapter. In some instances, the text I import might contain sentences I don't want (e.g., sentences with red rectangle in the image below) and thus I'd like to remove them before they make it to the chapter.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/22332927/8aef23be-d7da-4c8a-8f0b-dfc250606c00)

**Comment by simjanos-dev** [comment]
Will add in v0.9. I'm not sure why I did it this way.

**Comment by simjanos-dev** [comment]
Added it, it will be in the next update.
