### ISSUE TITLE
The dictionary search does not seem to work

### ISSUE THREAD

**Issue by onsosb** [simjanos-dev/LinguaCafe#180]
Hi,
I installed LinguaCafe, as instructed.  added DeepL API key for Spanish and also upload the Spanish dictionary.  Booth are enabled.  When I select a word from epub and text file that I have uploaded, nothing is displayed on the pop up , and the right hand side column also say did not find the word.  
Any idea what I could have done wrongly?
Thanks in advance.
Artimess

**Comment by simjanos-dev** [comment]
There is a **VERY** tiny chance, that you do not see DeepL results because you enabled it after you opened a text, and you did not refresh the opened text page, and you do not see dictionary results because you selected a rare word that the dictionary do not have.

It should look like this if it's working.

![test](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/561d514f-8fba-43bc-91f0-42154ed46d12)

**Comment by onsosb** [comment]
To answer your question:
1)  Yes,  it show information about dictionary loaded:
      wiktionary es	97,973	dict_es_wiktionary
2) I went to the network window I see a request for search each tile I hover over a world, but no errors, but I looked at the payload, to my surprise I see the payload uses Japanese as the source language, here is an example
Payload request:
(language: "japanese", term: "continuación"}
However I have only enabled DeepL Spanish and the downloaded  dictionary.
3) DeepL shows I have not used my monthly limit at all and I have 50000 free character left.

4) No I first enabled the DeepL ES and then uploaded the dictionary and then I opened my book to examine it

I guess I see the error as it is inquiring wrong dictionary, but how it decide to consider the payload a Japanese word, I have no idea.
Any further hints? and thanks for your help

**Comment by simjanos-dev** [comment]
> Any further hints? and thanks for your help

Yes, I think you did not select the Spanish language. Everything in Linguacafe is separated by the selected language. Just click on the selected language on the bottom left corner, and select Spanish. It will work after that.

I've received this feedback from multiple people. I've added this info to the [user manual](https://simjanos-dev.github.io/LinguaCafeHome#user-manual), but I'll think about a way to make it more intuitive.

**Comment by onsosb** [comment]
Thanks, that was it,  all works well now, and thank you so much for your help.

**Comment by simjanos-dev** [comment]
I'm glad it worked!

**Comment by onsosb** [comment]
Just occurred to me, it would be a good feature to select multiple words, aka a phrase or sentence to get the translation.  As DeepL could do it.  The catch is if it is a phrase, only a translator should be queried and not a dictionary

**Comment by simjanos-dev** [comment]
You can do that, and also save them as a phrase. After that the phrase will act a word.

There is a request to the dictionaries for phrases as well. The reason for this is that there are multi word phrases in dictionaries as well. And even if it finds none, the dictionary request is really fast, and does not cause performance issues.

**Comment by onsosb** [comment]
How do you do it, where is explained, I tried to select multiple words, but could not succeed ?

**Comment by simjanos-dev** [comment]
Just hold down the left mouse button, and drag it to the next word. You may need to hold down the button for 0.5 seconds before moving it, I'm not sure. I'll test it in a few hours. 

There is also a 13 word limit for it. 

If it does not work, it might be a bug. What browser do you use?

**Comment by onsosb** [comment]
I am using Brave , I will try it. Thanks;  By the it is a very nice system you have built

**Comment by simjanos-dev** [comment]
Thank you!

I am using it with Chromium, and tested on Firefox a few weeks ago. It may be a browser thing, I'm not sure. 


Brave also uses chrome's engine, so it is strange.

**Comment by onsosb** [comment]
This is my last stupid question, promise you it won't happen again.   I downloaded the dict.cc dictionary for Spanish.  But noticed it is not in the format to be used in Linguacafe.  Since it was suggested as an alternative, I am wondering if you have a utility to convert it to Linguacafe friendly format.
Thanks in advance.

**Comment by simjanos-dev** [comment]
> This is my last stupid question, promise you it won't happen again.

Please ask as many questions as you like, I'm happy to help.

> downloaded the dict.cc dictionary for Spanish. But noticed it is not in the format to be used in Linguacafe. Since it was suggested as an alternative, I am wondering if you have a utility to convert it to Linguacafe friendly format.

Just drop the file into the `linguacafe/stroage/app/dictionaries` folder. Then go to the Admin -> Dictionaries page, click on the Import dictionary button. The Spanish dictionary should show up here, and can import it by clicking on the Import button. Every dictionary in the readme can be installed this way.


I've just checked the text selection. There is no delay required, it works just like selecting text anywhere, except you have to start the selection on a word, you cannot select text if you start the mouse click on an empty space. Did it work for you? Can you try it out in an other browser? If there's a bug, I would like to fix it.

**Comment by onsosb** [comment]
Hi There,
Just to confirm, that I could upload the dict.cc worked fine.  Also,  I tried multiple word selection, it works sluggishly in Brave, but much better in Firefox.  So all is well and thanks a lot
