### ISSUE TITLE
[Proposal] Rename the "Finish reading" button to something clearer and purposeful

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#183]
I think the "Finish reading" button is a bit misleading. It stands for setting all words in this chapter to known, which isn't what I particularly associate with finishing reading a chapter, a book, etc. When I finish reading a chapter, for example, it simply means that I read it, not that I know all the words in it.

It's misleading because it leads the user into the false belief they need to click "Finish reading" to save the words they've marked as learning, ignored or even known, when in fact that isn't the case since the words get already saved automatically by assigning a level in the **Vocabulary sidebar**. 

I propose to rename it to something else (e.g., **Mark as known**, **Set to known**, **Know it!**, **Know 'em**, etc.), and possibly even bring up a dialog asking the user if they really want all the words in the chapter to become known since it cannot be undone, e.g., new words that are set to anything else cannot be set to new again, or at least that's my understanding and experience with LinguaCafe.

**Comment by simjanos-dev** [comment]
Good idea!

It also updates the daily read words goal/statistics. 

I think i should also add a function to set the level back to new for a word if someone wants that.

**Comment by uzluisf** [comment]
>I think i should also add a function to set the level back to new for a word if someone wants that.

This is a good idea as well!

**Comment by simjanos-dev** [comment]
Any suggestions for the new name? Mark/set as known is misleading, because the `auto set to known` option can be turned off. In that case it would only update statistics.

**Comment by simjanos-dev** [comment]
I can't come up with any name that would fit. Maybe:
- I could add a question mark icon with a popup info about what the button does.
- I could add a dialog after the user clicked on the button, and ask if they want to move their yellow words to known. But I think this would annoy people who already use the software and know what the button does, and it adds an extra step.
- Add a button to the toolbar that moves the yellow words to known, and set "auto move to known" option off as a default. This way the finish reading button would only update the statistics by default, and users have to turn on the "auto move to known" setting, and they will know what it does. 

Also, I think there should be a question mark + explanation on the settings dialog regardless which option we choose.

Do you have any thoughts or suggestions?

**Comment by uzluisf** [comment]
>I can't come up with any name that would fit. Maybe:

I think it's fine. I just noticed I had "Auto move words to known" enabled. I think adding a dialog pop-up with an explanation would be enough here, thus no need for renaming it.  

>Also, I think there should be a question mark + explanation on the settings dialog regardless which option we choose.

Absolutely! Something like "All new words will be moved to known when you click the **Finish reading** button."

![image](https://github.com/simjanos-dev/LinguaCafe/assets/22332927/28acec21-d738-4951-a7d6-b5c8bcfeaac6)

**Comment by uzluisf** [comment]
I submitted this https://github.com/simjanos-dev/LinguaCafe/pull/201 and I'd like to add a screenshot, however I cannot seem to import text into the (dev) database. I'm getting:

```
An error has occurred while importing your text.
```

Also looking at the Docker's container, LinguaCafe's Python service seems to be erroring out:

<details><summary>Error logs</summary>

```
2024-04-07 10:25:23 Traceback (most recent call last):
2024-04-07 10:25:23   File "/app/tokenizer.py", line 19, in <module>
2024-04-07 10:25:24     import lxml.html.clean
2024-04-07 10:25:24   File "/usr/local/lib/python3.10/dist-packages/lxml/html/clean.py", line 18, in <module>
2024-04-07 10:25:24     raise ImportError(
2024-04-07 10:25:24 ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
2024-04-07 10:25:24 Install lxml[html_clean] or lxml_html_clean directly.
```

</details> 

<img width="1494" alt="image" src="https://github.com/simjanos-dev/LinguaCafe/assets/22332927/a4a0abbf-a020-41db-a270-8c37db4e613c">

--- 

To get the development setup up:

1. Switched into `dev` and checked out a branch:

```
git switch dev
git checkout -b text-reader-known-words-dialog
```

2. Started the docker container and local server:

```
chmod -R 777 ./ && docker compose -f ./docker-compose-dev-macos.yml up -d --force-recreate
docker exec -ti linguacafe-webserver-dev npm run watch-poll
```

3. I created a new user and can navigate the UI fine, however I cannot import text to test the Text Reader.

**Comment by simjanos-dev** [comment]
It seems like there is a python package that changed, and the python text parser is not working because of it.

```
2024-04-07 10:25:24 ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
2024-04-07 10:25:24 Install lxml[html_clean] or lxml_html_clean directly.
```

I will look into this later and fix it. My PC is really slow with docker, so might take a while. If you would like to do do this yourself in the meantime:

Add to `docker/PythonDockerfile` and `docker/PythonDockerfileDev` files this line: `lxml[html_clean]` after `newspaper3k`. You will also need to add ` \` to the end of `newspaper3k`.

Then you will need to rebuild the docker image:
```
chmod -R 777 ./ && docker compose -f ./docker-compose-dev-macos.yml build && docker compose -f ./docker-compose-dev-macos.yml up -d --force-recreate
```

I haven't tried it yet, but it seems like it should work based on online comments. I will link this comment in discord as well. If someone did this and it works, please open a PR for it.

**Comment by simjanos-dev** [comment]
I have updated the dev branch, and fixed the issue. It was due to a new package change. Also updated contributing.md with instructions on how to update the dev environment if there's a change like this.

**Comment by uzluisf** [comment]
>I have updated the dev branch, and fixed the issue.

It's working now, thanks a lot! 🌟

**Comment by simjanos-dev** [comment]
This issue has been completed by merging #201.

**Comment by simjanos-dev** [comment]
I think I found a better design for this. It would be a [split button](https://tailwind.primevue.org/splitbutton/). If the user clicks on the arrow, they would get 3 checkboxes: 
- Increase read words statistics (this cannot be disabled) 
- Auto move words to known
- Update bookmark (bookmarks are not implemented yet)
- Plus any future behaviour tied to this button.


Vuetify (the UI library I use) does not support this, so I'll hack something together.
