### ISSUE TITLE
[Feature Request] User should interact with the vocabulary hover box only if interactive sentence mode is enabled

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#195]
During reviews, the user should be able to interact with the **Vocabulary hover box** only if **Interactive** sentence mode is enabled, otherwise they might be confused why it's not working when in **Plaintext** sentence mode, for example.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/22332927/e7b6121b-2190-40c4-9553-06d7ecae463e)

**Comment by simjanos-dev** [comment]
Do you think an info box about it in the settings dialog would work just as well?

**Comment by uzluisf** [comment]
>Do you think an info box about it in the settings dialog would work just as well?

This was more for less technically inclined people since if they can click things, then they expect some action to happen 😅. However an info box should work as well.

**Comment by simjanos-dev** [comment]
![reviewsettings](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/e02a2456-1db1-44da-8d42-1e60b9790941)

I've added in info box instead. I think it would not be unintuitive if some settings would disappear.
