### ISSUE TITLE
Cancel selecting a book cover

### ISSUE THREAD

**Issue by jacovanc** [simjanos-dev/LinguaCafe#197]
When creating a book, if you choose 'Change image' but then change your mind, there is no way to get finish creating the book without selecting an image (or cancelling the create book process completely and starting over).

This also applies for editing a book (although I would say it's fine here, just annoying on the original creation).

**Comment by simjanos-dev** [comment]
Thank you for the bug report!

It is already tracked in #186, the fix will be in the next update.
