### ISSUE TITLE
"Reversing" The default highlighted text 

### ISSUE THREAD

**Issue by onsosb** [simjanos-dev/LinguaCafe#223]
At present, all the text by default are initially highlighted (aka selected).  I think it would be much more readable  (easier to eyes) and perhaps more efficient, that the text be displayed  normally, and the reader chooses highlighting a word or words to consult the dictionaries and does other manipulations.
And once again, thanks for the application, it is really useful and fun to use it.

**Comment by simjanos-dev** [comment]
> At present, all the text by default are initially highlighted (aka selected).

Do you mean highlighted with yellow color? 

> And once again, thanks for the application, it is really useful and fun to use it.

I'm glad you find it useful. :)

**Comment by onsosb** [comment]
Yes, that's what I meant.  I think there are many words/prepositions etc. that a reader may know already, and highlighting everything makes the text convoluted  without any value added (in my humble opinion, of course).  The initial assumption should be that the reader knows everything by default unless he/she selects a word or words for doing the provided functions such as looking it up in the dictionaries, etc.
Cheers

**Comment by simjanos-dev** [comment]
> everything makes the text convoluted

At the very beginning, yes. But after reading for a while, there would only be a few new words for every page.

> The initial assumption should be that the reader knows everything by default unless he/she selects a word
> without any value added

I don't think so. The value added is that the software identifies new words for the user that they haven't seen before.

I'm not sure if you have found it, but there is a setting to hide yellow/new words highlighting in the text reader's settings.

I think it is an important feature, and should be left turned on as default. But I'll add info about it to the user manual to let users know they can turn it off.

I'll also do a poll on discord to find out which setting people prefer.

**Comment by onsosb** [comment]
Ok, yes, I did find the feature after posting my replay.  That's fine, now I know how I  can overcome it;  One note, in Eink theme, the enable/disable switch is hardly visible.  My browser is Brave and by default I am using the Dark theme, perhaps this is only for my browser, just as FYI I mentioned it.
Cheers and thanks again

**Comment by simjanos-dev** [comment]
> One note, in Eink theme, the enable/disable switch is hardly visible

Yeah, I really neglected e-ink theme. I haven't updated it for over half a year, so anything changed after that haven't been adapted to it. 

> My browser is Brave

If the bottom border type of highlighting for new words and disabled animations are not important for you in the e-ink theme, I would recommend using the light theme, and change the colors in the users settings to black and white and shades of them if you are using it on a led display.

**Comment by simjanos-dev** [comment]
Someone just told me that these settings are broken... I'll fix them and release an update in about an hour.
