### ISSUE TITLE
Parsing error where a parenthesis is considered part of a word

### ISSUE THREAD

**Issue by etherealite** [simjanos-dev/LinguaCafe#230]
Parser is doing some strange things with these parens.

First clicking on the word gave me this:
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/e074f987-9ba7-47c2-abae-ef3e4a3e9bf5)
Clicking on the left side parent resulted in this, where the Japanese paren `（` is now considered a word.
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/0df09975-72c6-4820-ad9c-b213af18608b)

Now all of the left Japanese parens are highlighted as words in the content text when they were not before were not.
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/eb339db2-40d9-4dfa-8f81-4ff6c8aee294)

Here it is in the word editor
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/941e7da6-4a13-404c-9e9b-15614966840c)

Copy and pasted DOM node of the `（` word from dev tools:
```HTML
<div wordindex="111" stage="2" phrasestage="learning" class="word highlighted" style="margin-bottom: 4px;"><ruby wordindex="111" class="rubyword">（<!----><!----></ruby><!----></div>
```

Copy and pasted DOM node of the `れんげ）` word from dev tools:
```HTML
<div wordindex="112" stage="1" phrasestage="learning" class="word" style="margin-bottom: 4px;"><ruby wordindex="112" class="rubyword">れんげ）<!----><!----></ruby><!----></div>
```
There are a couple areas in the content text where the parenthesis are of mixed type such as `（一穂(かずほ)）` combining ascii and Japanese parens.

No issue caused by this so far, figured it might be useful info.

**Comment by simjanos-dev** [comment]
I think this is either caused by the text parser library which is not perfect, or because my custom post processing function conjugates them accidentally. I think it's probably the second one.

In either way, I will fix this, so the parentheses will be treated as a separate word if it's at the beginning or end of a word.

A tip: If you find a Japanese word that's important to be separated, but it is incorrectly parsed, you can try adding a space before and after it, or if that does not work either, you can use [ ] around the word. That usually separates the word for me. 

Thank you for the detailed report again!

**Comment by etherealite** [comment]
Woops, found another one.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/cacc6068-42a8-4701-8be7-ab3d71a824eb)

 Looks like this may have been parsed correctly but the lemma reading and word readings got crossed together or something. Lemma is empty.
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/a2fbb8b5-fa3a-4b8c-82bd-f692237f0972)

**Comment by simjanos-dev** [comment]
It was a problem in my custom post processing function. I updated it, now it wont't combine words anymore which are in the words_to_skip list. (this list will be expanded in the future)

```
'words_to_skip' => ['。', '、', ':', '？', '！', '＜', '＞', '：', ' ', '「', '」', '（', '）', '｛', '｝', '≪', '≫', '〈', '〉',
        '《', '》','【', '】', '『', '』', '〔', '〕', '［', '］', '・', '?', '(', ')', ' ', ' NEWLINE ', '.', '%', '-',
        '«', '»', "'", '’', '–', 'NEWLINE', 'newline', ' ', "\r", "\n", "\r\n", '	', "\r\n　", ';', ',', '!', '\'', 
        '"', '‘', '_', '…', '/', '*', '&', '“', '”', '•', '©', '...', '●', '¡', '¿', '€', '$', '%', '˚', '°', '=', '!=', '-', '+'],
```

**Comment by etherealite** [comment]
Thanks for the quick fix!
