### ISSUE TITLE
For Japanese, bug where lemma is blank for word, word reading is off.

### ISSUE THREAD

**Issue by etherealite** [simjanos-dev/LinguaCafe#231]
Woops, found another one.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/cacc6068-42a8-4701-8be7-ab3d71a824eb)

 Looks like this may have been parsed correctly but the lemma reading and word readings got crossed together or something. Lemma is empty.
![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/a2fbb8b5-fa3a-4b8c-82bd-f692237f0972)

**Comment by simjanos-dev** [comment]
That's an interesting one. Can you please copy paste this word here?

**Comment by etherealite** [comment]
Sure thing, I have it right here from the raw file.

```
9
00:00:44,060 --> 00:00:52,000
もうそういう人は、僕が頑張って働くからこそ、日本ではゴールデンウィークを過ごせる人がいっぱいいるんだ。
```

**Comment by simjanos-dev** [comment]
Just a note. There's a known japanese issue with readings: #120.

**Comment by simjanos-dev** [comment]
That's a weird one. I deleted that single word from my database(don't do this on your production db), imported it again, and it is correct. I'll investigate this more in the future with a fresh database and I'll use the subtitle file to test it. Please comment here if you find multiple of this. I used Japanese, but haven't seen this problem before, or just haven't noticed because it's rare.

I also realized that I know this word, I just haven't been reading for a long time. :(

**Comment by etherealite** [comment]
Hey, I'm super impressed that you can keep up more than one language at a time. I hope I don't forget as well lol.

You remember this thought right?
助けてくれてありがとう!

**Comment by simjanos-dev** [comment]
> Hey, I'm super impressed that you can keep up more than one language at a time.

I'm not sure what you mean, I only learn Japanese.

> You remember this thought right?
助けてくれてありがとう!

Yes, I do!

**Comment by simjanos-dev** [comment]
Sorry, but I cannot replicate this. This is what I see when I use an empty database, create an .srt file from your example, and import it as a subtitle:

![ghissue](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/76fe7d17-6b6e-4645-80e8-6c452a187d35)


It is possible that it was imported from an other source first, and the inaccurate reading was generated there.

Are there maybe other words where you have kanji in your reading field? Or did you maybe use vocabulary import?

**Comment by etherealite** [comment]
That's alright, thanks for giving it a shot. I haven't had anything like this happen since, so I can't be of much help.

I'll be sure and report if I find this behavior again. You can close the issue.
