### ISSUE TITLE
Import stopped working for only one language

### ISSUE THREAD

**Issue by mateuszmrw** [simjanos-dev/LinguaCafe#263]
The import API returns with the Error 500 for any import for the Russian language.

It worked well yesterday for Russian, it still works for different languages. 
I have some books / yt videos already imported and they still work.

I included the error from the API in the file below.

The type of import for Russian does not matter, all of them fail.

Russian is mine most used language and I most of my imports are from this language. 
If you need more information please let me know.

API Error: [error.json](https://github.com/simjanos-dev/LinguaCafe/files/15332350/error.json)
Logs from Tokenizer: [tokenizer.txt](https://github.com/simjanos-dev/LinguaCafe/files/15332565/tokenizer.txt)

**Comment by simjanos-dev** [comment]
Same problem as #227. the bug fix will be released tomorrow, and I helped mateuszmrw to fix the corrupted database.
