### ISSUE TITLE
Disable scrolling on touch device when creating a new phrase 

### ISSUE THREAD

**Issue by mateuszmrw** [simjanos-dev/LinguaCafe#270]
Currently when using touch device and creating a phrase the scroll on the body and div element is enabled creating a bad UX for users, as selecting what we want to create a phrase from while screen scrolling up or down is confusing.

If the text is short enough is possible to refresh site on iPad when selecting text for phrase by scrolling down. This results in not being able to create a phrase.

I was thinking that adding a overflow: hidden on body and div with id #reader-content would be enough but after some playing around it seems there is more needed.

**Comment by simjanos-dev** [comment]
Fixed. Update will be out in 10~ minutes.
