### ISSUE TITLE
v0.12.1 - Book text not displayed in some browsers

### ISSUE THREAD

**Issue by pm3003** [simjanos-dev/LinguaCafe#272]
**The texts of the books are not displayed in some browsers**
After updating my instance to 0.12.1, the texts of the prevously downloaded books doesn't display on certain browsers.

**Affected version**
0.12.1 - the problem didn't exist on 0.11. Could not test on 0.12.0

**Browsers known to be affeced**
- Opera mobile (current version 82.3.4342.7950)
- Opera for Linux version 110.0.5130.23

Tested non-affected browsers : Firefox Linux, Qutebrowser (qtwebengine), Brave Linux, Vivaldi Linux, Vivaldi Android, Kiwi Browser.

**Description of the problem**
The text of the book is not displayed on certain browsers.
The HTML DIV "text-block-group....." is missing.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/48984ae8-05a4-4216-abf8-1336941dea9e)

**Expected behaviour : the page fetches the content correctly**

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/2ca7fde5-e801-4a8d-a9e9-da06c131a414)

**Comment by pm3003** [comment]
Screenshots from Opera errors. The qutebrowser errors are unrelated (failed requests because of server restarts).

![image](https://github.com/simjanos-dev/LinguaCafe/assets/5320421/c404b221-4944-48a6-a63a-9e25b966eb7c)

**Comment by simjanos-dev** [comment]
Thank you for the bug report!

I fixed it, you can download the new update in 20~ minutes.
