### ISSUE TITLE
Error uploading ebooks

### ISSUE THREAD

**Issue by onsosb** [simjanos-dev/LinguaCafe#275]
Hi,
I have been trying to upload ebooks in epub format.  and it laways fails.  I know for the fact that the ebooks are well formed and have no DRM. 
![image](https://github.com/simjanos-dev/LinguaCafe/assets/29179767/fd5281cd-22a0-46ed-bbe0-4078d184f36b)

It created an entry and it has nothing in it.  
Thanks,

**Comment by simjanos-dev** [comment]
Hi!

What operating system do you use? What linguacafe version do you use?

Did you use linguacafe v0.11.3 or below and updated, or started using it after v0.12 came out?

Can you please copy the output of your python docker container's terminal log here after you try to import a book? 


Without knowing the answers for any of these, I would try to: 
- Run `sudo chmod -R 777 ./storage/app/temp` from your linguacafe folder if you use linux or macos.
- Delete `./storage/app/temp` folder if you are using windows, and restart your server.

**Comment by onsosb** [comment]
To answer your questions:
1) No I am not using v0.12 for sure.  And is there any command  one can use to print Linguacafe running version
2) I am running on Linux (debian boolworm)
3) run chmod command you mentioned above, still did not work
4) I am ashamed of asking this but how do I get "python docker container's terminal log"?  I am not neither docker nor Linux expert!
Thanks

**Comment by onsosb** [comment]
FYI, I updated to the latest version, meaning v0.12,  I got the same error, if you wish and if you give a direct link/address I can send you the epub book in question

**Comment by simjanos-dev** [comment]
> FYI, I updated to the latest version, meaning v0.12, I got the same error

(If you just updated to v0.12, you had to run `sudo chmod -R 777 ./storage` for one last time to avoid permission issues.)

> if you wish and if you give a direct link/address I can send you the epub book in question

simjanos.dev@gmail.com

That would be great, thank you! I could rule out having a bug in linguacafe that comes out only in that specific book, but based on the previous comments, I think that is what the issue might be.

Can you import text manually? (It's possible that the database corrupted, and now every import fails due to this. It happened twice, it was fixed in v0.12)

**Comment by onsosb** [comment]
1) I update to the latest version
2) I run chmod   command
3) The importing the book failed again
4) Creating manually, meaning also fails.
5) Here is  docker log output, notice the very last line is when I tried manually copy and paste the text.
6) I will send the book to your email address.
Thanks

root@DietPi:~/linguacafe# docker logs -f linguacafe-python-service
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8678/
Hit Ctrl-C to quit.

/home/laravel/.local/lib/python3.10/site-packages/ebooklib/epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
/home/laravel/.local/lib/python3.10/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
172.18.0.4 - - [21/May/2024 14:58:43] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 15:08:09] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 15:55:26] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 15:56:47] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 15:57:01] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 16:00:47] "POST /tokenizer/import-book HTTP/1.1" 200 11187522
172.18.0.4 - - [21/May/2024 16:01:34] "POST /tokenizer/import-book HTTP/1.1" 200 11187522
172.18.0.4 - - [21/May/2024 16:07:20] "POST /tokenizer/import-book HTTP/1.1" 200 2495216
172.18.0.4 - - [21/May/2024 16:11:26] "POST /tokenizer HTTP/1.1" 200 31758

**Comment by simjanos-dev** [comment]
I got this in email:

> I think you are right it should be the corrupted data base. Now I cannot even import from web,  before it used to work.

Probably I can help you fix this. Please run this command to enter MySql.

```
docker exec -ti linguacafe-database mysql -ulinguacafe -plinguacafe
```

Then inside mysql, run these commands:
```
use linguacafe;
select id, words from phrases where words = '[]';
```

Do you get any records found?

**Comment by onsosb** [comment]
mysql> use linguacafe;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select id, words from phrases where words = '[]';
+----+-------+
| id | words |
+----+-------+
|  1 | []    |
+----+-------+
1 row in set (0.00 sec)

**Comment by simjanos-dev** [comment]
Please make a backup on your database before you do anything. 

You can delete this phrase inside mysql with this command:
```
delete from phrases where id = 1;
```

Then you must delete and re-import all your texts to be 100% sure that the database is correct. You can also click on the edit button for chapters and save them again if that's easier (except for subtitles, that cannot be edited).

Sorry about this. Not sure exactly what caused this, but it was fixed in v0.12, and it should not happen anymore.

There is a comment thread at #227 if you are interested in the details.

Please let me know if you managed to fix it, or if you need more help.

**Comment by simjanos-dev** [comment]
Hi!

Did you manage to fix your db?

**Comment by onsosb** [comment]
Hi, sorry, I thought I responded, it was exactly what you diagnosed it, yes all is well Thanks again Sent from my iPhoneOn Jun 5, 2024, at 9:00 PM, LinguaCafe ***@***.***> wrote:﻿
Hi!
Did you manage to fix your db?

**Comment by simjanos-dev** [comment]
I'm happy it worked! It should not happen anymore from v0.12 or higher.
