### ISSUE TITLE
Error in docker-compose file 'name' does not match any of the regexes

### ISSUE THREAD

**Issue by stereotypy** [simjanos-dev/LinguaCafe#318]
I'm getting the error `'name' does not match any of the regexes: '^x-'` with the default docker compose. It looks like the latest version no longer supports the name attribute, removing it worked.

**Comment by sergiolaverde0** [comment]
I think this happens because you are using the standalone `docker-compise` binary which was deprecated a long time ago and never supported the attribute. You should be using the modern `docker compose` extension instead.

According to the Compose Specification `name` is   a valid top level element.

**Comment by simjanos-dev** [comment]
@sergiolaverde0 We probably found the issue in  #312

**Comment by simjanos-dev** [comment]
@stereotypy Did you succeed installing linguacafe? I'm happy to help if I can.

**Comment by simjanos-dev** [comment]
I'll close this issue since it got no response for a month. Please feel free to open it again if you still have problems, I'm happy to help if I can.
