### ISSUE TITLE
Imported (supported) dictionaries do not have timestamps in the database.

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#322]

**Comment by cblanken** [comment]
I'd like to work on this issue. Are there any particular implementation concerns I should be aware of? I haven't looked at the code yet, but I'm assuming it should just be a matter of creating the timestamps when a dictionary is added or updated for the `created_at` and `updated_at` columns, right?

**Comment by simjanos-dev** [comment]
Yes, thats all. There are multiple import functions for different kinds of dictionaries.

Thank you for your help!

**Comment by simjanos-dev** [comment]
Fixed
