### ISSUE TITLE
Socket and Access denied for user 'root'@'localhost' in ./database/general-log.log

### ISSUE THREAD

**Issue by fbr1969** [simjanos-dev/LinguaCafe#327]
After installing Linguacafe, importing a dict.cc dictionary, creating a book and a chapter, I have a problem with the dictionary. No words are found. Looking at the SQL database log (./database/general-log.log), I see that I have a connection problem with the socket.

Do you have any idea on how to solve this problem? I haven't touched the docker-compose.yml file

`2024-08-15T09:17:40.653384Z        77 Connect   root@localhost on  using Socket
2024-08-15T09:17:40.653407Z        77 Connect   Access denied for user 'root'@'localhost' (using password: NO)
2024-08-15T09:17:50.683471Z        78 Connect   root@localhost on  using Socket
2024-08-15T09:17:50.683502Z        78 Connect   Access denied for user 'root'@'localhost' (using password: NO)
2024-08-15T09:18:00.732950Z        79 Connect   root@localhost on  using Socket
2024-08-15T09:18:00.732974Z        79 Connect   Access denied for user 'root'@'localhost' (using password: NO)
2024-08-15T09:18:10.779996Z        80 Connect   root@localhost on  using Socket
2024-08-15T09:18:10.780019Z        80 Connect   Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by simjanos-dev** [comment]
Hi!

Im sorry for the late response. 


I dont know what could be the problem. Someone else also has the same error message. I dont think its related, because if you could not connect to the db, other functions would not work either. 

Ill check the db error message, and see if I can reproduce. 

Did you select your language on the bottom left corner?

What language do you learn? Theres one or two dict cc dictionary that contains very few entries.

**Comment by fbr1969** [comment]
Hi!
I have selected French on the bottom left corner.
I have one dictionnary (dict.cc), for English to French translation (176,814 entry). 
It's strange, because everything is working fine, except the translation in a book, a chapter.
My system is a fresh installation of Linux Debian 12 and Docker Compose version v2.29.1

**Comment by simjanos-dev** [comment]
I dont know whats wrong, havent seen this issue before. Could you please screenshot the browsers network tab when you click on some words? I want to see what is being sent to the server and received. 

Can you also please try wiktionary? (Im not sure if theres a french one or not)

Ill probably have time to check if it works for me as well.

**Comment by fbr1969** [comment]
Hi,
Sorry for the delay and the poor resolution of my image, I am on a separate network.
![ecran](https://github.com/user-attachments/assets/5a3b5560-ef51-4c37-a76e-b93fb2460c7e)
I will look at Wiktionnary.
Best regards

**Comment by fbr1969** [comment]
Hi, 
I'm trying to check that my dictionary is consistent. Here is a sample of the CSV file that I imported. Can you tell me if in your opinion the data is correctly formatted? Linguacafe seems to import them correctly, but I don't have a translation.
Good to you.

> '18' film|film {m} interdit aux moins de 18 ans|noun|[film] 
's-Hertogenbosch [also Den Bosch]|Bois-le-Duc {f}|noun|[geogr.] 
(')Sup? [sl.] [idiom] [What's up?]|Ça va ? [loc.]||
(a) few|quelques-uns [peu]|pron|
(A) Journey to the Center of the Earth [Am.]|Voyage au centre de la Terre [Jules Verne]||[F] [lit.] 
(abundant) selection of sth.|assortiment {m} de qc.|noun|
(acting) fee|cachet {m} [paie]|noun|[film] [fin.] [theatre] 
(act of) betrayal|traîtrise {f}|noun|
(act of) incendiarism|incendie {m} volontaire|noun|[FireResc] 
(act of) sacrilege|sacrilège {m}|noun|[relig.] 
(a day's) holiday|jour {m} de congé|noun|
(advance) booking|réservation {f} [billets, etc.]|noun|
(advance) booking [seats]|location {f} [de spectacle]|noun|[theatre] 
(African) bare-eyed thrush|merle {m} cendré [Turdus tephronotus]|noun|[orn.] [T] 
(African) black eagle|aigle {m} de Verreaux [Aquila verreauxii]|noun|[orn.] [T] 
(African) black eagle|aigle {m} noir (d'Afrique) [Aquila verreauxii]|noun|[orn.] [T] 
(African) black eagle|aigle {m} noir à dos blanc [Aquila verreauxii]|noun|[orn.] [T] 
(African) black rhinoceros|rhinocéros {m} noir [Diceros bicornis]|noun|[T] [zool.] 
(African) black rhino [coll.]|rhinocéros {m} noir [Diceros bicornis]|noun|[T] [zool.] 
(African) blue quail|caille {f} bleue [Excalfactoria adansonii, syn. : Coturnix adansonii, C. adansoni, Synoicus adansonii]|noun|[orn.] [T] 
(African) crowned eagle|aigle {m} couronné [Stephanoaetus coronatus]|noun|[orn.] [T] 
(African) death's head hawkmoth|sphinx {m} tête de mort [Acherontia atropos]|noun|[entom.] [T] 
(African) dwarf bittern|blongios {m} de Sturm [Ixobrychus sturmii]|noun|[orn.] [T] 
(African) little sparrowhawk|épervier {m} minule [Accipiter minullus]|noun|[orn.] [T] 
(African) palm squirrel|écureuil {m} d'Ebi [Epixerus ebii]|noun|[T] [zool.] 
(African) palm squirrel|écureuil {m} des palmiers [Epixerus ebii]|noun|[T] [zool.] 
(African) palm squirrel|écureuil {m} palmiste [Epixerus ebii]|noun|[T] [zool.] 
(African) snakebird|anhinga {m} [Anhinga rufa]|noun|[orn.] [T] 
(African) snakebird|oiseau-serpent {m} [Anhinga rufa]|noun|[orn.] [T] 
(African) swallow-tailed kite|élanion {m} naucler [Chelictinia riocourii, syn. : Elanoides riocourii, Elanus riocourii]|noun|[orn.] [T] 
(African) white-backed vulture|vautour {m} africain [Gyps africanus]|noun|[orn.] [T] 
(African) yellow-billed duck|canard {m} à bec jaune [Anas undulata]|noun|[orn.] [T] 
(after-)effects {pl}|contrecoup {m}|noun|
(agricultural) crop|plante {f} utile|noun|[agr.] [bot.] 
(air) bubble|bulle {f} d'air|noun|
(air) terminal|aérogare {f}|noun|[aviat.] 
(aircraft) hangar|hangar {m} à avions|noun|[aviat.] 
(alarm) buzzer|avertisseur {m} sonore|noun|[FireResc] 
(alcoholic) spirit|eau-de-vie {f}|noun|[gastr.] 
(all) the world and his wife [coll.] [hum.]|tout le monde|pron|
(aluminium) foil [Br.]|papier {m} aluminium|noun|[gastr.] 
(aluminium) foil [Br.]|papier {m} alu [fam.]|noun|[gastr.] 
(aluminium) foil [Br.]|papier {m} d'aluminium|noun|[gastr.] 
(aluminum) foil [Am.]|papier {m} aluminium|noun|[gastr.] 

And another sample :

> economy class|classe {f} économique|noun|[aviat.] 
economy class|classe {f} éco [fam.]|noun|[aviat.] 
economy of scale|économie {f} d'échelle|noun|[econ.] 
economy|économie {f}|noun|
ecopolitical|en matière de politique environnementale|adj|[ecol.] [pol.] 
ecoregion [also: ecological region]|écorégion {f} [aussi : région écologique]|noun|[ecol.] [geogr.] 
ecosystem collapse|effondrement {m} écologique|noun|[ecol.] 
ecosystem|écosystème {m}|noun|[biol.] 
ecotourism|tourisme {m} vert [écotourisme]|noun|[ecol.] [travel] 
ecotourism|écotourisme {m}|noun|[ecol.] [travel] 
ecotoxicology|écotoxicologie {f}|noun|[chem.] [ecol.] [acad.] 
ecotrophology|œcotrophologie {f}|noun|[FoodInd.] [educ.] [acad.] 
ecozone [also: biogeographic realm]|écozone {f} [aussi : région biogéographique]|noun|[biol.] [geogr.] 
ecozone [also: ecological zone]|écorégion {f} [aussi : région écologique]|noun|[ecol.] [geogr.] 
ecru|écru [couleur] [beige]|adj|
ecstasy|assomption {f} [de l'esprit, de l'âme]|noun|
ecstatically|avec un enthousiasme délirant|adv|
ecstatic|extasié|adj|
ecstatic|extatique|adj|
ectopia lentis|luxation {m} du cristallin|noun|[dent.] 
ectopic|ectopique|adj|[med.] 
ectopic pregnancy|grossesse {f} extra-utérine <G.E.U.>|noun|[med.] 
ectoplasm|ectoplasme {m}|noun|[biol.]

**Comment by fbr1969** [comment]
Hi,
Thank you for your advice. I tried to use the  French.wiktionary.tsv. He works fine to translate a french text, but I need an english to french translation. So, I thing a need to build my own dictionnary with your exemple.

**Comment by simjanos-dev** [comment]
If you want to learn english, then you have to select english on the bottom left corner.
