### ISSUE TITLE
Database error.

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#331]
@sergiolaverde0 Hi! Any chance you know what could be wrong? A user got these error logs. 

Info:
- Default files.
- Fresh install.
- Windows 10, Docker Desktop, WSL2 integration with Debian

I don't have any ideas. Suggested them to delete the database folder, haven't got a response yet. Thought I would ask you as well, maybe you see something.

I'm a bit worried, because I sometimes get random errors like these on discord that I have no idea where they come from, or how to help the users. Hope it's because more people use the software, and not because it is getting more problems.

[linguacafe-webserver logs.txt](https://github.com/user-attachments/files/16666622/linguacafe-webserver.logs.txt)
[linguacafe-database logs.txt](https://github.com/user-attachments/files/16666623/linguacafe-database.logs.txt)

Thank you for your help in advance (even if you don't see anything either)!

**Comment by sergiolaverde0** [comment]
I wonder if they are running this on a rented remote server (VPS). The IP listed is a bit weird for something running on a local machine, but I cannot be certain. I will look into it more deeply this week.

**Comment by simjanos-dev** [comment]
I saw that too. I almost deleted the message with the logs, but double checked it, and it is a private ip.

> I will look into it more deeply this week.

Thank you! I am waiting for their response. Maybe just deleting the database will fix the issue.
