### ISSUE TITLE
The /dev endpoint response uses the dark mode background while in light mode

### ISSUE THREAD

**Issue by cblanken** [simjanos-dev/LinguaCafe#335]
The response component uses the dark mode background even when light mode is enabled.

## Light mode
![image](https://github.com/user-attachments/assets/5e156fb2-f162-445d-b54a-6c7ba3381114)

## Dark mode
![image](https://github.com/user-attachments/assets/b6f00dd4-2906-470e-9f35-668153cd35e8)

**Comment by simjanos-dev** [comment]
Thank you for the bug report! Fixed.
