### ISSUE TITLE
Automatic light / dark mode switching

### ISSUE THREAD

**Issue by cblanken** [simjanos-dev/LinguaCafe#342]
It would be awesome if LinguaCafe had an "Auto" theme option that could detect the system theme automatically according to the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media feature.

Additionally, an light/dark icon for the auto mode might be needed or combining the existing icons like this might suffice.
![image](https://github.com/user-attachments/assets/1d0ca7af-58c0-4ff5-a4b2-e6650e3ca130)

The "Auto" option should probably be displayed as the first item if it is made to be the default though.

**Comment by simjanos-dev** [comment]
Can this be done with Javascript? Otherwise it would not work.

**Comment by cblanken** [comment]
The `prefers-color-scheme` can be checked via JS with the [`Window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) method.

Here's an example implementation in React 
- https://medium.com/hypersphere-codes/detecting-system-theme-in-javascript-css-react-f6b961916d48.

**Comment by cblanken** [comment]
@simjanos-dev I'd like to try my hand at implementing this feature if you're amenable to it.

**Comment by simjanos-dev** [comment]
That would be great! I think it is in the Layout.vue file.

**Comment by cblanken** [comment]
Well this may be harder than I thought. Lots of hardcoded 'light' and 'dark' mode string checks. I'll have to think about how to implement this some more.

**Comment by simjanos-dev** [comment]
Sorry, my code is a mess in a lot of places. I'm working on fixing it.

I think it should be simple, you just have to: 
- load saved selected theme setting (Layout.vue line 202)
- if there's no saved theme, or the selected theme is auto, then you load the light or dark theme  based on the system colors

I don't think you should modify more for this, unless I misunderstood the feature you want to implement.

**Comment by simjanos-dev** [comment]
Implemented.
