### ISSUE TITLE
NaN displayed in the "Known words" field for new, empty books

### ISSUE THREAD

**Issue by cblanken** [simjanos-dev/LinguaCafe#349]
Super minor, but the `Known words` field on new books shows `NaN`. This should probably be set to an empty string or just `0` instead of showing the `NaN` to the user.

![image](https://github.com/user-attachments/assets/65c22117-150d-49eb-af6a-1983f94103d6)

**Comment by simjanos-dev** [comment]
Fixed. Thank you for the bug report!
