### ISSUE TITLE
Incorrect login redirect while behind a reverse proxy

### ISSUE THREAD

**Issue by DavisGoglin** [simjanos-dev/LinguaCafe#376]
I'm testing out this software behind a reverse proxy and am having issues with the 302 redirect to the login page. 

The external URL of the application is `https://linguacafe.example.com`, but on visiting it's giving a 302 redirect to `http://linguacafe.example.com/login`, notably http instead of https. 

Ideally the software uses the headers set by the reverse proxy to redirect correctly. 

The proxy in this case is Caddy, and it's setting the usual headers:

* X-Forwarded-For
* X-Forwarded-Proto
* X-Forwarded-Host

As a test I edited the line in `Http/Middleware/TrustProxies.php` to `protected $proxies = "[my proxy ip];` and that fixed the issue, but that variable isn't exposed as an env so this obviously isn't a long term solution. 

I also tried setting `APP_URL` env, but that didn't seem to make any changes. 

Is there a recommended way of getting this behavior?

A bonus would be able to authenticate using headers like `X-Token-User-Email` set from the proxy.

**Comment by simjanos-dev** [comment]
Hi! 

I don't know why this is happening, I never used a reverse proxy setup.

**Comment by simjanos-dev** [comment]
I think a few people on discord may have similar setups, you can try asking there as well.
