### ISSUE TITLE
Is there a way to make everything non-yellow?

### ISSUE THREAD

**Issue by kinow** [simjanos-dev/LinguaCafe#6]
I know a lot of Spanish words, but that's because it's very similar to Portuguese (my native language). I imported a book, and was planning to use it to go through the words that I do not understand. But with so many yellow words it becomes very hard to read it, and to mark the words that I am comfortable with (most due to PT & ES similarities).

Would it be possible to toggle everything non-yellow and then set the unknown words to some level, please?

Thank you!

**Comment by kinow** [comment]
BTW, happy to be the star number 100 of LinguaCafe :star: :tada: thanks a lot!

![Screenshot 2024-01-08 at 22-03-54 simjanos-dev_LinguaCafe LinguaCafe is a self-hosted software that helps language learners read foreign languages](https://github.com/simjanos-dev/LinguaCafe/assets/304786/7b5cef40-1b68-4565-81ae-4d01d190dd31)

**Comment by simjanos-dev** [comment]
Hi!

I added a task on my list to make an option to toggle yellow words only. There is an option to turn off all highlighted words(which is buggy when you hover over a word, also added). 

You can use this sql command temporarily to turn ALL your yellow words into "known" words:
UPDATE encountered_words SET stage = 0 WHERE stage = 2;

It won't affect highlighted words.

An other temporary fix: you can click on 'Finished reading' before you read a text, which will set yellow words to known, then reload the page, and don't click on 'Finished reading' when you actually finish it. 

Sorry, I'll try to implement the option soon.

**Comment by kinow** [comment]
>You can use this sql command temporarily to turn ALL your yellow words into "known" words:
UPDATE encountered_words SET stage = 0 WHERE stage = 2;

Brilliant! 

>Sorry, I'll try to implement the option soon.

No hurry, now I have a workaround :slightly_smiling_face: 

Thanks a lot!

**Comment by simjanos-dev** [comment]
The "Highlight words" option in the text and subtitle reader settings dialog has been split into 2 options: "Hide all highlighting" and "Hide new word highlighting". This makes it possible to hide only the yellow new word highlighting.

Also all visual hovering/selecting issues have been solved when highlighting is hidden.

It will be merged into the main branch as v0003 update in a few hours.

**Comment by kinow** [comment]
Thank you @simjanos-dev !
