### ISSUE TITLE
Dictionaries.

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#60]
I will keep a list of dictionaries I know about here and any additional information about them. 

- [x] CC-CEDICT for chinese
- [x] Wiktionary
- [x] Kengdic for korean
- [x] Eurfa Welsh Dictionary

If you have a recommendation for a dictionary, please comment it here.

**Comment by gelbziesel** [comment]
Hello! I was wondering if it would be possible to import the [Serbo-Croatian wiktionary](https://kaikki.org/dictionary/Serbo-Croatian/index.html)? I would do it myself but am not sure how to get it into the correct format.

**Comment by simjanos-dev** [comment]
Hi! 

I wanted to add support for kaikki wiktionaries for a while, just didn't get there yet. I am going to work on other stuff for a while.

You can import dictionaries into linguacafe in .csv format. If you write a script that converts kaikki's json to a .csv, you can import it into linguacafe.

Serbo-Croatian is also not supported in linguacafe currently. You can probably use Croatian for it, but the generated lemmas would probably be incorrect.
