### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by sergiolaverde0** [simjanos-dev/LinguaCafe#65]
After noticing that releases so far have been labelled as `v002` and `v0003`, I want to propose the adoption of [semantic versioning](https://semver.org), which will allow to identify at a glance is an updates introduces fixes, adds features, or makes breaking changes. With the upcoming adoption of ghcr.io to build and publish images, this is the right moment to do it so that all images published get proper version numbers which users can pin if they wish to do so.

Since project is still young I propose to label the next release as `v0.1.0` to reflect that software is still in pre-release status and breaking changes can happen between minor versions.

**Comment by simjanos-dev** [comment]
I'm not sure about this. The reason I've decided to go with the current system, is that 
- I do not want to differentiate fixes and and feature updates, most updates will have both. If i introduce this system I would be limited by it in each update. 
- I do not want to make breaking changes, if possible ever. If there is a need to change the database structure or stored files, I can write migrations. Everything that's not in the database or storage is copied to the images, which are basically replaced in each version and shouldn't cause a problem changing them completely.

What do you think about renaming previous releases(or just leaving them as they are now), using v0.4 for the next update, and only using two different digits? I could change to v1.0 in the future when it gets much more stable. People would understand better that it is still in `pre-release`, it looks better, and would still just be a simple +1 in each update.

**Comment by sergiolaverde0** [comment]
> * I do not want to differentiate fixes and and feature updates, most updates will have both. If i introduce this system I would be limited by it in each update.

I think the opposite. By adding a self imposed rule of updates having both fixes and features, it will make fixes arrive later to the users since they might get held back by unfinished features. This system, when paired with separate branches for each feature and for general bugfixes, allows for the later to be patched and published within the same day. Right now this is no big issue, but as project reaches maturity feature updates will be far more spread apart and most of the time will be spend fixing things that have already been added.

So next release could be v0.4.0 and you leave the door open for the next one to be either v0.5.0, v0.4.1, or v1.0.0. Restricting yourself to two digits will leave you with less choice for little gain.

**Comment by simjanos-dev** [comment]
> By adding a self imposed rule of updates having both fixes and features,

I didn't meant that I have that rule. I meant that right now I can have anything in a single update. I can have a single bugfix in it, a single feature, or as many bugfixes and features mixed as I want. 

I could also use v0.4, but if I want to introduce full semantic versioning in the future, I could start adding the third digit.

I'll think about it.

**Comment by simjanos-dev** [comment]
I think I want to go with v0.4, and if there will be a need for smaller patches, I'll introduce the third digit only for those: v0.4.1 v0.4.2 and so on. Then I'll go back to v0.5 in the next actual version.

Do you think that's okay? I prefer it this way. But if you still want me to always display the 3 digit, i'll go with that.

**Comment by sergiolaverde0** [comment]
That is good enough for me since updates will still broadcast their contents by their version numbers.
