### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by sergiolaverde0** [simjanos-dev/LinguaCafe#68]
As of the instant this issue is published, the GitHub Action is unable to build `arm64` images for the Python container. The build process fails during the step of `RUN python3 -m spacy download ja_core_news_sm` since it pulls `sudachipy` as a dependency, which does not support builds outside Windows and Linux in `x64`.

This means native images for Macs running Apple silicon and Raspberry Pis are not available.

For the time being, Mac users can run the software by adding the following line in their `docker-compose.yml` in the section for the python-service:

```
platform: linux/amd64
```

This represents a performance overhead since this workaround makes use of virtualization, and Raspberri Pis cannot make use of this.

**Comment by simjanos-dev** [comment]
Thank you! Should I add this to the readme?

**Comment by sergiolaverde0** [comment]
MySQL and the PHP image do seem to support ARM64 just fine. I am drafting a PR right now, will open it once I get a successful build (which takes ages in ARM), so that Mac people will run those two containers natively and virtualize the third one, and pray that doesn't break anything.

If that doesn't work they will have to bite the bullet and virtualize everything.

**Comment by sergiolaverde0** [comment]
Fixed by PR #70.

**Comment by simjanos-dev** [comment]
Should we do something about this when we add language model installing? Sudachipy is only used by Japanese. I've looked this issue up, because someone asked about installing it on raspberry pi and forgot what was the problem.

**Comment by sergiolaverde0** [comment]
Yeah this has been popping on the back of my head ever since we talked about making some languages optional.

We would need to communicate to the users that Japanese (and maybe other languages too) is not supported on ARM, both from the website, the announcement and the admin panel itself to prevent unnecessary bug reports and other. For now I think it is best to fully implement local models in dev and then add ARM support on top of that.

**Comment by simjanos-dev** [comment]
Okay. It's not something important, just someone asked and left a comment.
