### ISSUE TITLE
Database is not found on first launch

### ISSUE THREAD

**Issue by sergiolaverde0** [simjanos-dev/LinguaCafe#69]
It has been reported several times that when first starting the service stack, the PHP container fails to find the table it needs in the database container which makes the migration step fail. Every time it solves itself by restarting the stack and never happens again until a fresh install is attempted, and it doesn't always happen.

The hypothesis is that even after introducing a health check in the database container, the PHP container still rushes to do the migration as soon as it passes, and depending on hardware or even sheer luck with the health check timeouts it can attempt to do so while the database is in the process of creating the schema, which makes it to fail.

The solutions that cross my mind are:
- Add a `sleep` command to the entrypoint to make the PHP container wait for an arbitrary amount of time after the health check succeeds so that the database schema can be created.
- Add the same `sleep` which would get run the first time, then it updates an environment variable so it does not run after the first start.
- Make the PHP container re attempt the migration at certain intervals if the first attempt fails.

First one can be done in 15 seconds and while not exactly stylish, containers are not usually restarted so many times for it to be a dealbreaker. Usually.

Second one requires a little more effort and might encounter some edge cases.

Third one I don't have a clue how to do it or how complex it is, but would be probably ideal in the long term. It might even make the health check in the compose file redundant.

There is also the possibility of all this being plain wrong, only testing will tell.

**Comment by simjanos-dev** [comment]
Fixed.
