### ISSUE TITLE
import-jmdict: Symfony Maximum execution time of 600 seconds exceeded 

### ISSUE THREAD

**Issue by TrTai** [simjanos-dev/LinguaCafe#8]
On my current host I'm running the jmdict import by signing in then navigating to <hostip>:9191/jmdict/import-jmdict
the count reaches 18700 then encounters a Symfony FatalError due to maximum execution time. 

May impact slower machines with the current 600 second max execution time, (mine ended up being a bit  under 20 minutes to complete)  I worked around manually by changing the uploads.ini with sed since I already had it deployed, for others that may be concerned about it can edit the docker/PhpDockerfile and set it to a higher value or 0 to set to unlimited (not recommended just in case something goes awry)  

RUN printf 'max_execution_time = 600\n' >> /usr/local/etc/php/conf.d/uploads.ini

This may not be something that needs to be changed unless it affects a significant amount of people as 10 minutes should be a pretty good number, but in case anyone else runs into it while importing the dictionary files, there's a quick fix. 

Thanks!

**Comment by simjanos-dev** [comment]
Sorry, I kind of forgot about this open Issue, and forgot to respond. I've kept the 600 max execution time for everything else, but removed max execution time for importing dictionaries.
