### ISSUE TITLE
Install instructions fail with an error

### ISSUE THREAD

**Issue by atrussokc** [simjanos-dev/LinguaCafe#89]
Hello.  Thanks for your efforts to make Linguacafe. It seems very promising and I would like to use such a tool.  However, when running the commands from the github to install, it fails with an error.  It failed to register layer:  failed to Lchown...   I am stuck at this point.  Here is the output from the install attempt.

git clone -b deploy https://github.com/simjanos-dev/LinguaCafe.git linguacafe && cd linguacafe && chmod 777 -R ./ && docker compose up -d

Cloning into 'linguacafe'...
remote: Enumerating objects: 3371, done.
remote: Counting objects: 100% (918/918), done.
remote: Compressing objects: 100% (327/327), done.
remote: Total 3371 (delta 621), reused 830 (delta 567), pack-reused 2453
Receiving objects: 100% (3371/3371), 88.52 MiB | 27.34 MiB/s, done.
Resolving deltas: 100% (2215/2215), done.
[+] Running 20/22
 ⠦ webserver Pulling                                                           42.5s
   ⠿ 2f44b7a888fa Pull complete                                                 3.6s
   ⠿ 3a95dcec6035 Pull complete                                                 4.4s
   ⠿ e22afa33f327 Pull complete                                                11.6s
   ⠿ 1aa61ea11ee8 Pull complete                                                11.6s
   ⠿ ea67ae2bde33 Pull complete                                                12.8s
   ⠿ ff5356c6468f Pull complete                                                12.8s
   ⠿ 5e91cb51e886 Pull complete                                                12.8s
   ⠿ 935e88b21d5f Pull complete                                                13.0s
   ⠿ 8202e883ada1 Pull complete                                                13.0s
   ⠿ be40d3507d33 Pull complete                                                13.8s
   ⠿ 5fac4c1a6ab6 Pull complete                                                13.8s
   ⠿ 03fcb105f703 Pull complete                                                13.8s
   ⠿ 87c6b0d7fa4d Pull complete                                                13.9s
   ⠿ 397d4813a191 Pull complete                                                14.4s
   ⠿ 30946b957aa5 Pull complete                                                27.8s
   ⠿ ab049424edcc Pull complete                                                27.9s
   ⠿ 3aca3bd0ba79 Pull complete                                                27.9s
   ⠿ 3acb3df96127 Pull complete                                                27.9s
   ⠿ 380e61795a45 Pull complete                                                30.3s
   ⠿ 0fc28685344c Pull complete                                                32.3s
   ⠼ 8168a188d96e Extracting  115.7MB/115.7MB                                  41.4s
failed to register layer: failed to Lchown "/var/www/html/node_modules/brorand/.npmignore" for UID 120012366, GID 120012366 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /var/www/html/node_modules/brorand/.npmignore: invalid argument

I am running this in an LXC container on Proxmox. Running as root on an Ubuntu 23.10 version of Linux.

Any advice would be appreciated.  I will continue to follow the development of this.

**Comment by simjanos-dev** [comment]
Hi!

Sorry, but I have no idea what could cause this. I will try to figure it out. Any idea @sergiolaverde0 ?

I think it is related to how LXC [handles permissions](https://ubuntu.com/blog/custom-user-mappings-in-lxd-containers)?

**Comment by atrussokc** [comment]
Thank you for responding so quickly.  I just tried this again on an existing Proxmox Ubuntu 23.10 VM (not LXC container) and it is working.  This issue is likely related to the LXC permissions as you stated.  Please close this issue.

Thanks

**Comment by sergiolaverde0** [comment]
I haven't used LXC before but I think support for it would be a good idea. This has also reminded me to try to use podmsn too to be sure it works as well (it should by default).

I will look into this later on, but might take a while.

**Comment by harabat** [comment]
@sergiolaverde0 I run podman on Manjaro, I ran into this issue around a week ago, just checked now and it's still happening. 

My `/etc/subuid` and `/etc/subgid` contain the line `user:100000:65536`. 

<details>
<summary>Error message</summary>

```
$ git clone -b deploy https://github.com/simjanos-dev/LinguaCafe.git linguacafe && cd Cloning into 'linguacafe'...
remote: Enumerating objects: 3371, done.
remote: Counting objects: 100% (918/918), done.
remote: Compressing objects: 100% (328/328), done.
remote: Total 3371 (delta 620), reused 829 (delta 566), pack-reused 2453
Receiving objects: 100% (3371/3371), 88.52 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (2215/2215), done.
>>>> Executing external compose provider "/usr/bin/podman-compose". Please refer to the documentation for details. <<<<

podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.8.3
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=linguacafe', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'linguacafe_linguacafe']
podman run --name=linguacafe-database -d --label io.podman.compose.config-hash=b8f1029b306538ef1eb2df02d80475bf942b248e996465617df62e01237654c5 --label io.podman.compose.project=linguacafe --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@linguacafe.service --label com.docker.compose.project=linguacafe --label com.docker.compose.project.working_dir=/home/user/LinguaCafe/linguacafe --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=mysql -e MYSQL_DATABASE=linguacafe -e MYSQL_USER=linguacafe -e MYSQL_PASSWORD=linguacafe -e MYSQL_ROOT_PASSWORD=linguacafe -e SERVICE_NAME=linguacafe -v /home/user/LinguaCafe/linguacafe/database:/var/lib/mysql --net linguacafe_linguacafe --network-alias mysql -p 3308:3306 --tty --restart unless-stopped mysql:8.0 mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
61ec6d4084e31fa3edfe5f3376b3cbbb31ed1c6c021a12e4bc349d61c4fab204
exit code: 0
['podman', 'network', 'exists', 'linguacafe_linguacafe']
podman run --name=linguacafe-python-service -d --label io.podman.compose.config-hash=b8f1029b306538ef1eb2df02d80475bf942b248e996465617df62e01237654c5 --label io.podman.compose.project=linguacafe --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@linguacafe.service --label com.docker.compose.project=linguacafe --label com.docker.compose.project.working_dir=/home/user/LinguaCafe/linguacafe --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=python -v /home/user/LinguaCafe/linguacafe/storage:/var/www/html/storage --net linguacafe_linguacafe --network-alias python --tty --restart unless-stopped ghcr.io/simjanos-dev/linguacafe-python-service:main /app/manage.py runserver 0.0.0.0:8678
9fa8e2824038928dee3b82f2d1fcec2d9791391fe9b57a9711ed6343e09bdce1
exit code: 0
['podman', 'network', 'exists', 'linguacafe_linguacafe']
podman run --name=linguacafe-webserver -d --requires=linguacafe-database --label io.podman.compose.config-hash=b8f1029b306538ef1eb2df02d80475bf942b248e996465617df62e01237654c5 --label io.podman.compose.project=linguacafe --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@linguacafe.service --label com.docker.compose.project=linguacafe --label com.docker.compose.project.working_dir=/home/user/LinguaCafe/linguacafe --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=webserver -v /home/user/LinguaCafe/linguacafe/storage:/var/www/html/storage --net linguacafe_linguacafe --network-alias webserver --add-host host.docker.internal:host-gateway -p 9191:80 -p 3000:3000 ghcr.io/simjanos-dev/linguacafe-webserver:main
Trying to pull ghcr.io/simjanos-dev/linguacafe-webserver:main...
Getting image source signatures
Copying blob 1aa61ea11ee8 skipped: already exists
Copying blob 3a95dcec6035 skipped: already exists
Copying blob ff5356c6468f skipped: already exists
Copying blob ea67ae2bde33 skipped: already exists
Copying blob e22afa33f327 skipped: already exists
Copying blob 5e91cb51e886 skipped: already exists
Copying blob 2f44b7a888fa skipped: already exists
Copying blob 935e88b21d5f done   |
Copying blob 8202e883ada1 done   |
Copying blob be40d3507d33 done   |
Copying blob 5fac4c1a6ab6 done   |
Copying blob 03fcb105f703 done   |
Copying blob 87c6b0d7fa4d done   |
Copying blob 397d4813a191 done   |
Copying blob 30946b957aa5 done   |
Copying blob ab049424edcc done   |
Copying blob 3aca3bd0ba79 done   |
Copying blob 3acb3df96127 done   |
Copying blob 380e61795a45 done   |
Copying blob 0fc28685344c done   |
Copying blob 8168a188d96e done   |
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:8168a188d96ee5172b0f03920e2c75fa159817369df1580846df8e20b646a891": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 120012366:120012366 for /var/www/html/node_modules/brorand/.npmignore): Check /etc/subuid and /etc/subgid if configured locally and run "podman system migrate": lchown /var/www/html/node_modules/brorand/.npmignore: invalid argument): exit status 1
exit code: 125
podman start linguacafe-webserver
Error: no container with name or ID "linguacafe-webserver" found: no such container
exit code: 125
```

</details>

**Comment by sergiolaverde0** [comment]
I haven't used LXC before but I think support for it would be a good idea. This has also reminded me to try to use podmsn too to be sure it works as well (it should by default).

I will look into this later on, but might take a while.

**Comment by sergiolaverde0** [comment]
Thanks for the detailed error report, it seems to be the same issue as LXC and further confirms it is due to permissions.

**Comment by sergiolaverde0** [comment]
@harabat Could you check if you have the newuidmap binary by running `type newuidmap`? I would expect yes but some Arch-based systems are a bit too minimal for their own good.

**Comment by sergiolaverde0** [comment]
It seems like the podman side has had this issue [for years](https://github.com/containers/podman/issues/12715) and requires a bit of [manual intervention](https://www.redhat.com/sysadmin/rootless-podman) for a fix. So much for a drop-in replacement. LXC has the same issue and is also fixed the same way, run under privileges or map more users.

I think it is theoretically possible for us to provide a image that runs as an unprivileged user inside the container which might fix this issue, but it will almost certainly break compatibility with already existing installs which has happened enough times over the last _two weeks_.

Plus I am mentally fatigued of trying to reconcile Laravel and Docker, those two don't play along well.

**Comment by simjanos-dev** [comment]
I think we should close this issue. I don't want to provide multiple images with breaking changes.

**Comment by simjanos-dev** [comment]
It seems like 2 people on Reddit were able to run it in LXC containers. I leave their comment here.

[link](https://www.reddit.com/r/selfhosted/comments/1ae6deo/comment/ko9do6f/?utm_source=share&utm_medium=web2x&context=3)

Comment:

> I just installed this on my debian lxc. I'm still learning docker but as long as you have docker and git installed on your lxc. Copy and paste the git link in the detailed instructions, I saw it pulled in Python and a webserver. Waited for it to finish and then just go to your promox IP:
> 
> eg: http://192.168.1.189:9191/
> 
> Create a user, log in to GUI and follow rest of the instructions for downloading dictionaries.

Response:

> Thanks for sharing some details. I tried this again today and it just worked!! I am not sure what I was struggling with exactly as I attempted pretty much the same steps!
