### ISSUE TITLE
Add a way to use a different target language for deepl translation

### ISSUE THREAD

**Issue by Einenlum** [simjanos-dev/LinguaCafe#93]
I think it would be nice for people like me who are not English native speakers.

It seems it's hardcoded to English right now ([here](https://github.com/simjanos-dev/LinguaCafe/blob/main/app/Http/Controllers/DictionaryController.php#L183)).

This would also require to store the target language in the cache.

**Comment by simjanos-dev** [comment]
People also have asked for adding english language. I will have to think about how to add more deepl combinations.

**Comment by Einenlum** [comment]
I guess this could be selected in a dropdown (in the admin/deepl section), with languages coming from [this API call](https://www.deepl.com/docs-api/general/get-languages).
People should be able to translate into a language that is not handled by LinguaCafe, IMO. Because it's just a hint for them and it doesn't impact the behavior of the software (on the contrary to adding English language, which is a more impacting feature).

**Comment by simjanos-dev** [comment]
I agree. When I wrote about having to think about how to add more dictionaries, I meant that they are added automatically now. I will probably keep the default English ones that are already there, and if someone wants to add another language pair for DeepL, they will have to add a DeepL language pair manually in the `Import dictionary` menu.

**Comment by simjanos-dev** [comment]
@Einenlum 

I've added the option to change the language for DeepL in every language. It will be out in the next update. 

I will add an option to add multiple DeepL languages in a later update.
