### ISSUE TITLE
Refresh vocabulary page after an edit

### ISSUE THREAD

**Issue by Einenlum** [simjanos-dev/LinguaCafe#94]
If I change the level of a word in my vocabulary list, data is not refreshed after in the list, which is quite confusing.

![1](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/1f5f1009-e6ff-4a25-9d85-76a04c0d2fdb)

![2](https://github.com/simjanos-dev/LinguaCafe/assets/5675200/6339134b-617f-401e-9974-1fbe85c99a2c)

**Comment by simjanos-dev** [comment]
Thabk you! I will fix it. Also the weird level button color.

**Comment by simjanos-dev** [comment]
Fixed it, will be in v0.7 update. 

Also fixed an issue that caused the order of records to be random inside the specified `Order by` parameter. So each time you refreshed the page, the order of records were different, or if you had multiple pages of items, then they could also appear on different pages. Now every record will be at the same place.

The dialog will also close by its own after saving it.
