### ISSUE TITLE
Set the level for a lemma instead of word?

### ISSUE THREAD

**Issue by Einenlum** [simjanos-dev/LinguaCafe#96]
Right now it seems like the level can only be set for a word and not a lemma.

For example, "ist", "bin" and "sein" are rightfully detected as the lemma "sein" in German, but setting "bin" to a certain level only applies to "bin". I still have to set it for all the versions of the lemma.

It could be an interesting feature to be able to optionally set it to the whole lemma.

**Comment by simjanos-dev** [comment]
Yes, it is a planned feature. #43. Right now every word is treated as a different word.

I haven't thought about it in detail, but the way you described it seems mores simple to develop than I thought it would be. The only problem would be if someone turns on this option, and they already have different translations saved for the 2 different words with the same lemma, then one of them would be overwritten. But I guess that's inevitable.

It will take a while to implement this.

I updated the other issue and added level to it as well, and will close this one, so it is only tracked at one place.
