### ISSUE TITLE
High resource usage when deploying on Hetzner

### ISSUE THREAD

**Issue by harabat** [simjanos-dev/LinguaCafe#98]
I'm deploying LinguaCafe on Hetzner with 4GB RAM, Debian 11, Docker 25.0.1, LinguaCafe latest.

My CPU generally runs at 30-50%, but once the LinguaCafe containers start, resource usage shoots through the roof and my whole server becomes sluggish, and often completely unresponsive. The process responsible for this is `/bin/python /app/manage.py runserver 0.0.0.0:8678`. 

Don't know if it's connected, but I haven't been able to import a single book, even short ones, as I'm getting `An error has occurred while importing your text.` every time, whether I try simple or complex import. 

Would be glad to help diagnose further. 

Deploying locally (Manjaro) and importing books works.

**Comment by simjanos-dev** [comment]
Hi!

I am running on and old laptop, and I also have performance issues when I start it up for the first time after a fresh install. After that, it does not cause more problems for me. I've allocated 2 CPU cores and 2.3GB for my docker. 

The problem with python was that it loaded all language models, and and could use over 1.4GB ram. I've just pushed an update which replaces the Django server in the python container with Bottle, which is a much smaller server, and also added dynamic loading for language models, so it will only load them when you first import something on that language.

Most languages have only 10MB~ models, but some languages (Japanese, Korean, Russian, Ukrainian and Chinese) multiple hundred MB sized dependencies. 

I'm hoping this will fix some of the the performance issues. I will look more into it.

If you want to test the new image, you can if you add a `.env` file to your folder and add `VERSION=dev` text to it. then pull the new docker images. This is for testing purposes only, do not use it for production! Also, I haven't got the chance to test the image, only on my dev environment, so it is possible that it does not work yet.

**Comment by harabat** [comment]
@simjanos-dev this solved both my problems, thanks! The app seems to be working perfectly, importing books is a breeze. 

I will test more this evening and over the weekend, will let you know if I notice any issue with the new image.

**Comment by simjanos-dev** [comment]
Thank you. But please do not use this image in production. It will be updated throughout develoment, and can contain breaking changes/mess up your data. 

The next main version will be out sometime in february. 

Sadly it did not solve my problem. My laptop froze for 10~ minutes after pulling and deploying this image. :/

**Comment by simjanos-dev** [comment]
After further testing and confirming that RAM usage is significantly lower and it solved your problem, I am going to close this Issue. Please open it again if you still have problems after v0.7 is out. I would like to improve it more if possible.
